services:
  whisperx:
    extends:
      file: compose.yaml
      service: whisperx
    image: swang62/subtitle-generator:gpu
    labels:
      - wud.watch=false
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
