services:
  subtitle-generator:
    container_name: subtitle-generator
    build:
      context: .
      dockerfile: Dockerfile
    image: swang62/subtitle-generator
    environment:
      - MEDIA_FOLDER=/media
    ports:
      - 7860:7860
    tty: true
    restart: unless-stopped
    volumes:
      - ${MEDIA_FOLDER}:/media:rw
      - ./models:/models
