services:
  subtitle-generator:
    extends:
      file: compose.yaml
      service: subtitle-generator
    build:
      args:
        BASE_IMAGE: ubuntu:22.04
    image: swang62/subtitle-generator:cpu
