services:
  whisperx:
    container_name: whisperx
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - HF_TOKEN=${HF_TOKEN}
      - DEFAULT_MODEL=${DEFAULT_MODEL:-base}
    ports:
      - 7860:7860
    tty: true
    restart: unless-stopped
    volumes:
      - ${MEDIA_FOLDER}:/media:rw
      - ${TORCH_HOME:-./models/torch}:/.cache/torch
      - ${HF_HOME:-./models/huggingface}:/.cache/huggingface
