[project]
name = "subtitle-generator"
version = "0.1.0"
description = "Automatically generate subtitles for video/audio files using whisperx"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "fastapi>=0.121.1",
  "ffmpeg-python>=0.2.0",
  "gradio>=5.49.1",
  "hf-xet>=1.2.0",
  "pymediainfo>=7.0.1",
  "python-dotenv>=1.2.1",
  "torch==2.8.0",
  "torchaudio==2.8.0",
  "torchvision==0.23.0",
  "uvicorn>=0.38.0",
  "whisperx>=3.7.4",
]

[dependency-groups]
dev = ["pre-commit>=4.4.0"]

[tool.uv.sources]
torch = [
  { index = "gpu", marker = "platform_machine == 'x86_64' or platform_machine == 'AMD64'" },
]
torchvision = [
  { index = "gpu", marker = "platform_machine == 'x86_64' or platform_machine == 'AMD64'" },
]
torchaudio = [
  { index = "gpu", marker = "platform_machine == 'x86_64' or platform_machine == 'AMD64'" },
]

[[tool.uv.index]]
name = "gpu"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

[tool.ruff]
target-version = "py313"
extend-select = ["I"]

[tool.mypy]
python_version = "3.13"
ignore_missing_imports = true
