# Constants

MODELS = {
    "base": "default (fastest, least accurate)",
    "distil-large-v3": "large-distilled (fast, best for en)",
    "large-v3-turbo": "large-turbo (slow, good accuracy)",
    "large-v2": "large-v2 (slowest, most accurate)",
}
SUPPORTED_EXTENSIONS = (
    ".mp3",
    ".mp4",
    ".wav",
    ".avi",
    ".mov",
    ".flv",
    ".mkv",
    ".webm",
)
LANGUAGE_OPTIONS = {
    "Arabic": "ar",
    "Chinese": "zh",
    "English": "en",
    "French": "fr",
    "German": "de",
    "Greek": "el",
    "Hebrew": "he",
    "Hindi": "hi",
    "Italian": "it",
    "Japanese": "ja",
    "Korean": "ko",
    "Portuguese": "pt",
    "Russian": "ru",
    "Spanish": "es",
    "Turkish": "tr",
    "Vietnamese": "vi",
    "Unknown (auto-detect)": None,
}
DEFAULT_ALIGN_MODELS_TORCH = {
    "de": "VOXPOPULI_ASR_BASE_10K_DE",
    "en": "WAV2VEC2_ASR_BASE_960H",
    "es": "VOXPOPULI_ASR_BASE_10K_ES",
    "fr": "VOXPOPULI_ASR_BASE_10K_FR",
    "it": "VOXPOPULI_ASR_BASE_10K_IT",
}
DEFAULT_ALIGN_MODELS_HF = {
    "ar": "jonatasgrosman/wav2vec2-large-xlsr-53-arabic",
    "ca": "softcatala/wav2vec2-large-xlsr-catala",
    "cs": "comodoro/wav2vec2-xls-r-300m-cs-250",
    "da": "saattrupdan/wav2vec2-xls-r-300m-ftspeech",
    "el": "jonatasgrosman/wav2vec2-large-xlsr-53-greek",
    "eu": "stefan-it/wav2vec2-large-xlsr-53-basque",
    "fa": "jonatasgrosman/wav2vec2-large-xlsr-53-persian",
    "fi": "jonatasgrosman/wav2vec2-large-xlsr-53-finnish",
    "gl": "ifrz/wav2vec2-large-xlsr-galician",
    "he": "imvladikon/wav2vec2-xls-r-300m-hebrew",
    "hi": "theainerd/Wav2Vec2-large-xlsr-hindi",
    "hr": "classla/wav2vec2-xls-r-parlaspeech-hr",
    "hu": "jonatasgrosman/wav2vec2-large-xlsr-53-hungarian",
    "ja": "jonatasgrosman/wav2vec2-large-xlsr-53-japanese",
    "ka": "xsway/wav2vec2-large-xlsr-georgian",
    "ko": "kresnik/wav2vec2-large-xlsr-korean",
    "lv": "jimregan/wav2vec2-large-xlsr-latvian-cv",
    "ml": "gvs/wav2vec2-large-xlsr-malayalam",
    "nl": "jonatasgrosman/wav2vec2-large-xlsr-53-dutch",
    "nn": "NbAiLab/nb-wav2vec2-1b-nynorsk",
    "no": "NbAiLab/nb-wav2vec2-1b-bokmaal-v2",
    "pl": "jonatasgrosman/wav2vec2-large-xlsr-53-polish",
    "pt": "jonatasgrosman/wav2vec2-large-xlsr-53-portuguese",
    "ro": "gigant/romanian-wav2vec2",
    "ru": "jonatasgrosman/wav2vec2-large-xlsr-53-russian",
    "sk": "comodoro/wav2vec2-xls-r-300m-sk-cv8",
    "sl": "anton-l/wav2vec2-large-xlsr-53-slovenian",
    "sv": "KBLab/wav2vec2-large-voxrex-swedish",
    "te": "anuragshas/wav2vec2-large-xlsr-53-telugu",
    "tl": "Khalsuu/filipino-wav2vec2-l-xls-r-300m-official",
    "tr": "mpoyraz/wav2vec2-xls-r-300m-cv7-turkish",
    "uk": "Yehor/wav2vec2-xls-r-300m-uk-with-small-lm",
    "ur": "kingabzpro/wav2vec2-large-xls-r-300m-Urdu",
    "vi": "nguyenvulebinh/wav2vec2-base-vi-vlsp2020",
    "zh": "jonatasgrosman/wav2vec2-large-xlsr-53-chinese-zh-cn",
}
